name: rs-teszt
workers:

  - name: app
    envs:
      - key: FOO
        scope: RUN_AND_BUILD_TIME
        value: lorem
      - key: BAR
        scope: RUN_AND_BUILD_TIME
        value: ipsum
    dockerfile_path: Dockerfile
    github:
      repo: innovabin-agent/rs-teszt
      branch: main
      deploy_on_push: true
